pipeline {
  environment {
    registry = "yatulchik/devops-itea"
    registryCredential = 'dvs78mvg6vkj'
    dockerImage = ''
  }
  agent any
  stages {
    stage('Cloning Git') {
      steps {
        git 'https://github.com/Yatulchik/DevOps-itea'
      }
    }
    stage('Building image') {
      steps{
        script {
          dockerImage = docker.build ("nginx-custom-html + :$BUILD_NUMBER", "homework/nginx/")
        }
      }
    }
    stage('Deploy Image') {
      steps{
        script {
          docker.withRegistry( '', registryCredential ) {
            dockerImage.push()
          }
        }
      }
    }
    stage('Remove Unused docker image') {
      steps{
        sh "docker rmi nginx-custom-html:$BUILD_NUMBER"
      }
    }
  }
}
